[build]
  # Diretório de build
  publish = "dist"
  
  # Comando de build
  command = "npm run build"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"

# Headers de segurança globais
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers específicos para arquivos de build
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para arquivos HTML
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configuração de SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Redirecionamento de API para backend
[[redirects]]
  from = "/api/*"
  to = "https://filazero-sistema-de-gestao.onrender.com/api/:splat"
  status = 200
  force = true
